### ISSUE TITLE
MetFrag not functionning with java versions problem being compiled by a more recent version of the Java Runtime (52.0 and 55.0)

### ISSUE THREAD

**Issue by EmmEys** [rickhelmus/patRoon#91]
Hello,

I hope you are doing well.

The MetFrag CL package cannot load compounds because of a java error. Is there a way to fix the issue?

Best regards and thank you for your time!
Emmanuel

P.S. Here is the log error with the example data:

-------------------
command: java
args: -jar C:/Users/REF_Organique/Documents/patRoon-install/MetFragCommandLine-2.5.0.jar C:\Users\REF_OR~1\AppData\Local\Temp\RtmpCWkvRB\parameters36cc6eab7723.txt

---

output:

standard error output:
Exception in thread "main" java.lang.UnsupportedClassVersionError: de/ipbhalle/metfrag/commandline/CommandLineTool has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Exception in thread "main" java.lang.UnsupportedClassVersionError: de/ipbhalle/metfrag/commandline/CommandLineTool has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Exception in thread "main" java.lang.UnsupportedClassVersionError: de/ipbhalle/metfrag/commandline/CommandLineTool has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)

---------------------

**Comment by EmmEys** [comment]
I found it! I only had to get a more recent version of java. I assumed the one that can be downloaded [here](https://www.java.com/download/ie_manual.jsp) was the most recent but it was only version 8. I had to create an account and then install a more recent one (in this case version 21)
